### PR TITLE
fixes memcache sessions and cache

### PR DESCRIPTION
**Pull request by bshaffer**

### CODE REVIEW

**Comment by bshaffer** [comment]
@tmatsuo @dovy PTAL

@dovy - if you're up to the challenge, pull down my fork with the below commands and see if this works for you:

```
git checkout -b bshaffer-fixes-memcache-sessions-and-cache master
git pull https://github.com/bshaffer/appengine-symfony-starter-project.git fixes-memcache-sessions-and-cache
composer install
```

**Comment by tmatsuo** [comment]
Looks good, I think we should add some tests though. We can add tests later.

**Comment by bshaffer** [comment]
Absolutely! Added #8

**Comment by bshaffer** [comment]
@dovy you can just clone the latest branch using the instructions in the `README` now that this is in master

**Comment by dovy** [comment]
Yup, worked for me.  ;)

**Pull request merged**
